version: '3.4'

services:
  feedapp.api:
    image: ${DOCKER_REGISTRY-}feedappapi
    build:
      context: .
      dockerfile: FeedApp.Api/Dockerfile

  feedapp.service:
    image: ${DOCKER_REGISTRY-}feedappservice
    build:
      context: .
      dockerfile: FeedApp.Service/Dockerfile

