version: '3.4'

services:
  feedapp.api:
    image: ${DOCKER_REGISTRY-}feedappapi
    build:
      context: .
      dockerfile: FeedApp.Api/Dockerfile
    environment:
        - ConnectionStrings__PostgreSql="Host=localhost;Username=postgres;Password=;Database=testdb"
        - RabbitMq__Hostname="localhost"
        - RabbitMq__QueueName="polls"
        - RabbitMq__UserName="guest"
        - RabbitMq__Password="guest"

  feedapp.service:
    image: ${DOCKER_REGISTRY-}feedappservice
    build:
      context: .
      dockerfile: FeedApp.Service/Dockerfile
    environment:
        - ConnectionStrings__PostgreSql="Host=localhost;Username=postgres;Password=;Database=testdb"
        - RabbitMq__Hostname="localhost"
        - RabbitMq__QueueName="polls"
        - RabbitMq__UserName="guest"
        - RabbitMq__Password="guest"
